# Generated by Django 2.1.5 on 2020-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(max_length=5)),
                ('serial_id_last', models.CharField(max_length=5)),
                ('public_year', models.IntegerField()),
                ('city_id', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(max_length=500)),
                ('hospital_type', models.CharField(max_length=50)),
                ('dpc_bed_calcu', models.IntegerField()),
                ('hospital_charge_type', models.CharField(max_length=50)),
                ('dpc_bed_rate', models.FloatField()),
                ('recovery_bed_num', models.IntegerField()),
                ('regional_care_bed_num', models.IntegerField()),
                ('mental_bed_num', models.IntegerField()),
                ('recuperation_bed_num', models.IntegerField()),
                ('tuberculosis_bed_num', models.IntegerField()),
                ('bed_number', models.IntegerField()),
                ('public_month', models.IntegerField()),
            ],
        ),
    ]
