# Generated by Django 2.1.5 on 2020-03-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_cd', models.CharField(max_length=5)),
                ('postal_cd_old', models.CharField(max_length=5)),
                ('postal_cd', models.CharField(max_length=7)),
                ('prefecture_name_kana', models.CharField(max_length=50)),
                ('city_name_kana', models.CharField(max_length=50)),
                ('cyo_name_kana', models.CharField(max_length=50)),
                ('prefecture_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('cyo_name', models.CharField(max_length=50)),
                ('multi_postal_per_cyo', models.IntegerField()),
                ('have_small_ban', models.IntegerField()),
                ('have_cyome', models.IntegerField()),
                ('multi_cyo_per_postal', models.IntegerField()),
                ('update_flg', models.IntegerField()),
                ('reason_flg', models.IntegerField()),
            ],
        ),
    ]
